[workspace]
members = [
    "chain-core",
    "chain-impl-mockchain",
    "cardano",
    "network-grpc",
    "protocol",
    "protocol-tokio",
    "storage-units",
    "storage",
    "cardano-c",
    "exe-common",
]
